#ifndef _SVZ_DEFS_H_
#define _SVZ_DEFS_H_

#define IMAGE_MAX_WIDTH 1000
#define IMAGE_MAX_HEIGHT 1000
#define IMAGE_MAX_BITS IMAGE_MAX_WIDTH * IMAGE_MAX_HEIGHT
#define IMAGE_MAX_INDEXES (IMAGE_MAX_BITS / 32) + 1

#endif // _SVZ_DEFS_H_
